### ISSUE TITLE
Only test email is working

### ISSUE THREAD

**Issue by Choxmi** [deliciousbrains/wp-offload-ses-lite#3]
I've entered API secrets and configured the plugin and I can sent test mails as well. It's working fine.

But when I'm using `wp_mail()` from php code, it does not work. I couldn't find any response either. Is there any other fields to define? Any help would be much appreciated.

**Comment by mattgrshaw** [comment]
Hi,

Did you get this sorted? If not, you'd likely need to enable debug logging by editing your wp-config.php file and replace this line - 

`define( 'WP_DEBUG', false );`

With these lines - 

```
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false); 
```

This means that any errors are logged to `/wp-content/debug.log`, because some errors are not visible on screen. More details about that at http://codex.wordpress.org/Editing_wp-config.php#Debug 

That should give you some additional insight on why they aren't sending.
